project:
  type: website

website:
  title: "Bite-sized_workshop"
  navbar:
    left:
      - text: "R Series"
        menu:
        - text: "Episode 6"
          href: Rseries/Episode6.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

